apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: agent
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/imdb2-default: "true"
        io.kompose.service: agent
    spec:
      containers:
        - image: portainer/agent:2.11.1
          name: portainer-agent
          ports:
            - containerPort: 9001
              hostPort: 9001
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: agent-claim0
            - mountPath: /var/lib/docker/volumes
              name: agent-claim1
      restartPolicy: Always
      volumes:
        - name: agent-claim0
          persistentVolumeClaim:
            claimName: agent-claim0
        - name: agent-claim1
          persistentVolumeClaim:
            claimName: agent-claim1
status: {}
