apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api-tcp
  name: api-tcp
spec:
  ports:
    - name: "12345"
      port: 12345
      targetPort: 12345
  selector:
    io.kompose.service: api
  type: LoadBalancer
status:
  loadBalancer: {}
