apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/imdb2-api-auth: "true"
        io.kompose.network/imdb2-auth: "true"
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: secret
            - name: PGDATABASE
              value: postgres
            - name: PGHOST
              value: users-db
            - name: PGPASSWORD
              value: "1234"
            - name: PGUSER
              value: postgres
          image: octaviantorcea/imdb2:imdb2_auth-v2.0
          name: auth
          ports:
            - containerPort: 8089
              hostPort: 8089
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
