apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/imdb2-api: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: movies
            - name: MYSQL_PASSWORD
              value: tema
            - name: MYSQL_ROOT_PASSWORD
              value: tema
            - name: MYSQL_USER
              value: tema
          image: mysql:latest
          name: db
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-movies
            - mountPath: /docker-entrypoint-initdb.d/movies.sql
              name: db-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/c/Users/bogdan/Desktop/facultate/cc/imdb2
          name: mysql-movies
        - hostPath:
            path: /mnt/c/Users/bogdan/Desktop/facultate/cc/imdb2/business_logic/movies.sql
          name: db-hostpath1
status: {}
