version: '3.5'

services:
  users-db:
    image: postgres
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./auth/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - auth

  auth:
    image: octaviantorcea/imdb2:imdb2_auth-v2.0
    container_name: auth
    labels:
      kompose.service.type: LoadBalancer
    restart: always
    ports:
      - "8089:8089"
    environment:
      JWT_SECRET: secret
      PGUSER: postgres
      PGPASSWORD: 1234
      PGDATABASE: postgres
      PGHOST: users-db
    networks:
      - auth
      - api-auth
    depends_on:
      - users-db

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tema
      MYSQL_DATABASE: movies
      MYSQL_USER: tema
      MYSQL_PASSWORD: tema
    ports:
      - '3306:3306'
    volumes:
      - mysql-movies:/var/lib/mysql
      - ./business_logic/movies.sql:/docker-entrypoint-initdb.d/movies.sql
    networks:
      - api

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: pma
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - api

  api:
    image: octaviantorcea/imdb2:imdb2_api-v2.0
    container_name: api
    labels:
      kompose.service.type: LoadBalancer
    restart: always
    ports:
      - "12345:12345"
    depends_on:
      - db
    networks:
      - api
      - api-auth

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8885:8080"
    environment:
      DOZZLE_REMOTE_HOST: tcp://api:12345,tcp://auth:8089

networks:
  api:
  api-auth:
  auth:

volumes:
  mysql-movies:
  data:
