apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/imdb2-auth: "true"
        io.kompose.service: users-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: users-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: users-db-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/c/Users/bogdan/Desktop/facultate/cc/imdb2/auth/init.sql
          name: users-db-hostpath0
status: {}
