apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "12345"
      port: 12345
      targetPort: 12345
      nodePort: 30001
  selector:
    app: api
  type: NodePort
