apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
      nodePort: 30002
  selector:
    app: auth
  type: NodePort
