apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: octaviantorcea/imdb2:imdb2_api-v2.0
          name: api
          ports:
            - containerPort: 12345
      restartPolicy: Always
