apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: db
            - name: PMA_PORT
              value: "3306"
          image: phpmyadmin
          name: pma
          ports:
            - containerPort: 80
      restartPolicy: Always
