apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-db
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: users-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-db-initdb
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
        - name: user-db-initdb
          configMap:
            name: user-db-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-initdb-config
data:
  initdb.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(50) NOT NULL,
      password VARCHAR(255) NOT NULL,
      email VARCHAR(50) UNIQUE NOT NULL
    );
