apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  ports:
    - name: "9443"
      port: 9443
      targetPort: 9443
      nodePort: 30004
  selector:
    io.kompose.service: portainer
  type: NodePort
