apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: portainer-pvc
  name: portainer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
