apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/imdb2-auth: "true"
        io.kompose.service: users-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: users-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: users-db-claim0
            - name: user-db-initdb
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
        - name: users-db-claim0
          persistentVolumeClaim:
            claimName: users-db-claim0
        - name: user-db-initdb
          configMap:
            name: user-db-initdb-config
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-initdb-config
data:
  initdb.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(50) NOT NULL,
      password VARCHAR(255) NOT NULL,
      email VARCHAR(50) UNIQUE NOT NULL
    );
